version: '3.8'

services:
  hot_line_db:
    image: postgres:15-alpine
    container_name: hot_line_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hot_line
    ports:
      - "6755:5432"
    volumes:
      - hot_line_db_data:/var/lib/postgresql/data
    networks:
      - hot_line_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d hot_line"]
      interval: 5s
      timeout: 5s
      retries: 5

  hot_line_api:
    build:
      context: .
    container_name: hot_line_api
    ports:
      - "6710:6710"
      - "6711:6711"
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=hot_line_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hot_line
    depends_on:
      hot_line_db:
        condition: service_healthy
    networks:
      - hot_line_network

volumes:
  hot_line_db_data:
    driver: local

networks:
  hot_line_network:
    external: true